name: Elías García
description: >
    Desarrollador web full-stack.
    Escribo artículos sobre las últimas tecnologías web como Angular, Node.js y JavaScript en general.
meta_description: >
    "Soy Elías García, ingeniero informático y desarrollador web full-stack.
    Escribo artículos sobre las últimas tecnologías web como Angular, Node.js y JavaScript en general."

homeTitle: Artículos sobre Angular, Node.js y JavaScript
aboutPage: true

markdown: kramdown
highlighter: rouge

gems:
    - jekyll-seo-tag
    - jekyll-paginate
    - jekyll-feed
    - jekyll-sitemap

paginate: 10
basepath: /
domain_name: 'https://eliasgarcia.es'
google_analytics: 'UA-93475150-1'
disqus: true
disqus_shortname: 'elias-garcia'

# Details for the RSS feed generator
url:                    'https://eliasgarcia.es'
author:                 'Elías García'
authorTwitter:          'egarciadev'
authorGithub:           'elias-garcia'
authorStackOverflow:    'elias-garcia'

permalink:       /:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
