# Site settings
title: Elías García - Artículos sobre JavaScript en español
email: elias@eliasgarcia.es
description: >
  Soy Elías García, ingeniero informático y desarrollador web Full Stack.
  Escribo artículos sobre Node JS, Angular y JavaScript en general.
baseurl: ""
url: "https://eliasgarcia.es"
twitter_username: egarciadev
github_username:  elias-garcia
stack_overflow_username:  elias-garcia
google_analytics: UA-93475150-1
disqus_shortname: elias-garcia

# Post permalinks settings
permalink: /:title

# Pagination settings
paginate: 10

# Sass settings
sass:
    style: compressed

# Build settings
timezone: Europe/Madrid
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
