# Site settings
title: Elías García - JavaScript articles
email: elias@eliasgarcia.es
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "https://eliasgarcia.es"
twitter_username: egarciadev
github_username:  elias-garcia
stack_overflow_username:  elias-garcia
google_analytics: UA-93475150-1
disqus.shortname: elias-garcia

# Permalinks settings
permalink: none

# Pagination settings
paginate: 10

# Sass settings
sass:
    style: compressed

# Build settings
timezone: Europe/Madrid
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
